### PR TITLE
added some Open Source components from Synopse

### PR DESCRIPTION
**Pull request by synopse**
Added some of our Open Source classes and units, as stand-alone projects if they are used but uncoupled from the main mORMot project.
Also created a missing "Reporting" section.

### CODE REVIEW

**Comment by Fr0sT-Brutal** [comment]
Thanks, I replied you in Issue, this will take some time

**Comment by Fr0sT-Brutal** [comment]
Added almost all suggestions manually, remaining ones will follow soon

**Comment by Fr0sT-Brutal** [comment]
Thanks again for PR and respect for your work it's really titanic.

**Comment by synopse** [comment]
Thanks to you for including our units to your resource!

**Pull request closed without merging**
